### ISSUE TITLE
get session cookie?

### ISSUE THREAD

**Issue by bradyguyc** [Luca3317/OpenLibrary.NET#11]
Is there away to get the session cookie?  I am starting to work on creating/adding a book.   I need to PostJsonAsync with the session cookie. 

I don't think this includes the session cookie in the post correct?

OLClient.BackingClient.PostAsJsonAsync

Thanks

`
public async Task PostBookToOLAsync(Book book)
{

    if (!OLClient.LoggedIn)
    {

        await LoginWithUserName().ConfigureAwait(false);
    }

    var bookData = new
    {
        title = book.BookTitle,
        authors = new[] { new { name = book.Author } },
        publish_date = book.PublishDate,
        source_records = new[] { "amazon:" + book.ISBN_13 },
        number_of_pages = book.pageCount,
        publishers = new[] { book.publisher },
        isbn_10 = book.ISBN10.Count == 0 ? new List<string>() { book.ISBN_10 } : book.ISBN10,
        isbn_13 = book.ISBN13.Count == 0 ? new List<string>() { book.ISBN_13 } : book.ISBN13
    };

    var httpClient = OLClient.BackingClient;
    httpClient.DefaultRequestHeaders.Accept.Clear();
    httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

    var json = JsonConvert.SerializeObject(bookData);
    var stringContent = new StringContent(json, Encoding.UTF8, "application/json");
    Uri url = new Uri($"https://openlibrary.org/api/import.json");

    var response = await OLClient.BackingClient.PostAsJsonAsync(url, json);
    //var response = await httpClient.PostAsync("https://openlibrary.org/api/import", stringContent);

    if (response.IsSuccessStatusCode)
    {
        var responseJson = await response.Content.ReadAsStringAsync();
        Console.WriteLine(responseJson);
    }
}
`

**Comment by Luca3317** [comment]
Not at my computer right now but spontaneously Id say that OpenLibraryClient's HttpClient is configured to automatically include the session cookie. Will check in a bit when Im on my laptop.

**Comment by Luca3317** [comment]
Yeah, the session cookie is included in post requests made through the BackingClient.

**Comment by bradyguyc** [comment]
Thanks so much for the quick response
