### ISSUE TITLE
Use of Polly in the library?

### ISSUE THREAD

**Issue by bradyguyc** [Luca3317/OpenLibrary.NET#21]
I am wrapping most at somepoint all of my calls to openlibrary.net in polly pipeline.ExecuteAsync or ExecuteOutcomeAsync  primarily to enable retry and implement rate limiters.   I am finding that when I am making alot of calls I can exceed what the device can handle.  I think it's mostly on my device and overloading the thread pool (or whatever the appropriate term is ) I am doing a lot of learning in this area right now as I work with Parallel.ForEach etc... at any rate as I am doing this I wonder if the library itself should wrap the api calls in polly for retry and rate limiting etc.... Thinking out loud on this one.... 

Brady

**Comment by Luca3317** [comment]
I considered doing that a few months ago but ultimately decided against it so you dont have that dependency on polly and can use another rate limiter etc. if you prefer. Im not really set on this though so Im open to counterarguments.

**Comment by bradyguyc** [comment]
After working with polly for awhile there are just so many variables and options I agree that you should leave that to be done outside of the library.
