### ISSUE TITLE
The requestAsync and LoadAsAsync do not appear to be in OpenLibraryUtility or exposed there.  Is this an issue?

### ISSUE THREAD

**Issue by bradyguyc** [Luca3317/OpenLibrary.NET#3]
The requestAsync and LoadAsAsync do not appear to be in OpenLibraryUtility or exposed there.  Is this an issue?

Requests
Provides basic methods for making web requests. Uses private static HttpClient.

Also provides method to request and then parse data.

public async static Task<string> RequestAsync(string url);
public async static Task<T> LoadAsAsync<T>(string url, string path = "");

// Examples
string response = OpenLibraryUtility.RequestAsync("https://openlibrary.org/authors/OL274606A.json");
OLWorkData[] workData = OpenLibraryUtility.LoadAs<OlWorkData>("https://openlibrary.org/authors/OL274606A/works.json", "entries");
// Note: The work collection is the "entries" variable in the json response of the given url.
// The path parameter in LoadAsAsync is the path within the json structure.

**Comment by Luca3317** [comment]
It's been a while since Ive used any of this code myself, but IIRC there should be no harm in adding either of these.
Ill look through the code as soon as i find the time to make sure.

Spontaneously, Id say Id more likely just make the current LoadAsync and RequestAsync public instead of adding new method (ergo you would still have to pass in a HTTPClient instance).
Would that still serve your purpose?

**Comment by bradyguyc** [comment]
Yes that would work I believe.  
I was looking for away to call https://openlibrary.org/people/mekBot/books/want-to-read.json

I was thinking that the request and load methods might work here.

I did take your code and build locally and exposed the session cookie so I could make these calls after logging in.

I could make these two methods public as well and see if that works on my own.  

Thanks

**Comment by Luca3317** [comment]
I see, just saw they added a MyBooks API since I last checked openlibrary. 
Seems very small and simple, so will most likely add support for that tomorrow.

I'll still make Request and Load public for flexibility's sake

**Comment by bradyguy** [comment]
Thanks for the quick response.  I exposed loadasync in my copy and it worked fine for the my books api.   This is great library.   I had started to work on one but must say your code structure is far superior that what I was starting.   Thanks Agin!

**Comment by Luca3317** [comment]
Ill be updating the Nuget package later tonight with these changes, if you want to switch to that.

**Comment by Luca3317** [comment]
Updated the package now, sorry for the delay
