### ISSUE TITLE
have you noticed an issue with login

### ISSUE THREAD

**Issue by bradyguyc** [Luca3317/OpenLibrary.NET#8]
I all of sudden have problems with login not working.  Have you experienced the same?

**Comment by Luca3317** [comment]
Just tested it, no such issue for me. Are you using the nuget package version 0.1.3?

**Comment by bradyguyc** [comment]
yes, good to know it's just on my end.  In theory that should be solvable.  Thanks for the help.  It started not working when I rebuilt and had to put in my username and password again to my app.  But debugging it all looks the same.... geez...  

Again thanks

**Comment by Luca3317** [comment]
I see, good luck debugging. Just in case thats it, dont forget you log in with your email, not your username.

**Comment by bradyguyc** [comment]
so this is whats interesting, I was previously loging in with my username and it worked, if I tried logging in with my email it would not.   Now I can't seem to login with either.  I updated my local copy of openlibrary.net and added some debug statements and I can see where it things my email id is invalid.   So I will try changing my email id and see if that helps.   Thanks

**Comment by bradyguyc** [comment]
So changing my email seemed to do the trick.  I switched back to using your nuget package as well and it works with both  my local copy and your nuget package.   So now on to trying to add a book now that I can login again.  

As a suggestion I wonder if you could parse through the response and look for the error message that comes back in the html.   It said invalid email address.  I added a line to output the response content and siffed through that to find out what the server was sending back.  

Thanks for checking in your environment that helped!
